kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-rdb-claim
spec:
  accessModes:     
    - ReadOnlyMany
  storageClassName: dynamic-ceph-rdb
  resources:
    requests:
      storage: 20Gi
