apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config5
  namespace: default
data:
  cache_host: memcache-gcxt
  cache_port: "11211"
  cache_prefix: gcxt
  my.cnf: |
    [mysqld]
    log-bin = mysql-bin
    hahaha = hehehehehehe
