apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: konga-ingress
  annotations:
    kubernetes.io/ingress.class: outside
spec:
  rules:
  - host: konga.test.com
    http:
      paths:
      - path: 
        backend:
          serviceName: konga
          servicePort: 1337

