---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test-ingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`www.test.com`)
    kind: Rule
    services:
    - name: my-service
      port: 80
