---
# 应该先行deployment先部署,初始化数据库
apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations-inside
  namespace: kong
spec:
  template:
    metadata:
      name: kong-migrations-inside
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - kong migrations bootstrap
        env:
        - name: KONG_PG_PASSWORD
          value: "123"
        - name: KONG_PG_HOST
          value: postgres-inside
        - name: KONG_PG_PORT
          value: "5432"
        image: kong:1.3
        name: kong-migrations
      initContainers:
      - command:
        - /bin/sh
        - -c
        - until nc -zv $KONG_PG_HOST $KONG_PG_PORT -w1; do echo 'waiting for db';
          sleep 1; done
        env:
        - name: KONG_PG_HOST
          value: postgres-inside
        - name: KONG_PG_PORT
          value: "5432"
        image: busybox
        name: wait-for-postgres
      restartPolicy: OnFailure
