apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange-default
spec:
  limits:
  - default:
      memory: 64Mi
      cpu: 1
    defaultRequest:
      memory: 32Mi
      cpu: 200m
    max:
      memory: 256Mi
      cpu: 2
    min:
      memory: 16Mi
      cpu: 100m
    type: Container

