apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv3
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/dir3
    server: 192.168.99.105
