apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  annotations:
    prometheus.io/scrape: "true"
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "MysqlExporter"
spec:
  ports:
    - name: mysql-metrics
      port: 9104
      protocol: TCP
      targetPort: 9104
  selector:
    app: mysql-exporter
