---
kind: Service
apiVersion: v1
metadata:
  name: nginx-test
spec:
  type: NodePort
  selector:
    app: nginx-test
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 8800
    targetPort: 80
