---
kind: Service
apiVersion: v1
metadata:
  name: nginx-test
  annotations:
    prometheus.io/probe: 'true'
spec:
  selector:
    app: nginx-test
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
