apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  namespace: kong
spec:
  containers:
  - name: mypod1
    image: busybox:1.31
    args:
    - /bin/sh
    - -c
    - sleep 30000
    ports:
    - name: testport
      protocol: TCP
      hostPort: 8800
      containerPort: 80
      
