apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  namespace: kube-system
spec:
  containers:
  - name: mypod1
    image: busybox:1.31
    args:
    - /bin/sh
    - -c
    - sleep 30000
    ports:
    - name: testport
      protocol: TCP
      hostPort: 8888
      containerPort: 8888
  #  volumeMounts:
  #  - name: mydata
  #    mountPath: /data
  #  - name: rabbitmq-erlang-cookie
  #    mountPath: /data/.erlang.cookie
  #    subPath: .erlang.cookie
  #volumes:
  #- name: mydata
  #  persistentVolumeClaim:
  #    claimName: ceph-rdb-claim
  #- name: rabbitmq-erlang-cookie
  #  configMap: 
  #    name: rabbitmq-erlang-cookie
  #    items:
  #    - key: .erlang.cookie
  #      path: .erlang.cookie
