apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
  - name: mypod1
    image: busybox:1.31
    args:
    - /bin/sh
    - -c
    - sleep 30000
    ports:
    - name: testport
      protocol: TCP
      hostPort: 8888
      containerPort: 8888
#    volumeMounts:
#    - name: secret
#      mountPath: /data
#  volumes:
#  - name: secret
#    secret:
#      secretName: rbd-provisioner-token-r6q28
