apiVersion: v1
kind: Pod
metadata:
  name: mypod2
  namespace: default
spec:
  containers:
  - name: mypod2
    image: busybox:1.31
    args:
    - /bin/sh
    - -c
    - sleep 30000
    ports:
    - name: testport
      protocol: TCP
      hostPort: 8888
      containerPort: 8888
      
