---
# postgresql

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-outside
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-outside
  serviceName: postgres-outside
  template:
    metadata:
      labels:
        app: postgres-outside
    spec:
      nodeSelector:
        app1: kong
      containers:
      - env:
        - name: POSTGRES_USER
          value: kong
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_DB
          value: kong
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        image: postgres:10-alpine
        name: postgres-outside
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: postgres-data
      terminationGracePeriodSeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "sc-rbd"
      resources:
        requests:
          storage: 20Gi
