apiVersion: v1
kind: Service
metadata:
  name: postgres-inside
  namespace: kong
spec:
  ports:
  - name: pgql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-inside
