---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-ds
  labels:
    app: rabbitmq-ds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec: 
      nodeName: test102
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8.1-management
        ports:
        - name: port1
          containerPort: 15672
        - name: port2
          containerPort: 5672
        volumeMounts:
        - name: timefile
          mountPath: /etc/localtime
          readOnly: yes
        - name: rabbitmq-conf
          mountPath: /etc/rabbitmq
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: rabbitmq-erlang-cookie
              key: .erlang.cookie

      volumes:
      - name: timefile
        hostPath:
          path: /etc/localtime
      - name: rabbitmq-conf
        configMap:
          name: rabbitmq-conf
      #- name: rabbitmq-erlang-cookie
      #  secret:
      #    secretName: rabbitmq-erlang-cookie
