---
apiVersion: v1
kind: Secret
metadata:
  name: authsecret
  namespace: default
data:
  users: |2
    dGVzdDE6JGFwcjEkcUg3MEQyVmYkazFKQ3czVHRwNC9KVjNURTkvUW1aLyB0ZXN0MjokYXByMSRM
    UzNQS1RDUSQwM2NOS1dSMUxMZGFKN3ZqcmJVT3gwCg==
