apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-rbd
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.99.104:6789,192.168.99.105:6789,192.168.99.106:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: kube-system
  pool: kube
  userId: admin
  userSecretName: ceph-secret
  userSecretNamespace: kube-system
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"
