kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dynamic-cephfs
provisioner: ceph.com/cephfs
reclaimPolicy: Retain
parameters:
    monitors: 192.168.99.104:6789,192.168.99.105:6789,192.168.99.106:6789
    adminId: admin
    adminSecretName: ceph-secret
    adminSecretNamespace: "kube-system"
    claimRoot: /volumes/kubernetes
