---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ds
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: 
      nodeSelector:
        app: nginx
      containers:
      - name: nginx
        image: nginx:1.15
        ports:
        - containerPort: 80
        volumeMounts:
        - name: timefile
          mountPath: /etc/localtime
        - name: webdir
          mountPath: /usr/share/nginx/html

      volumes:
      - name: timefile
        hostPath:
          path: /etc/localtime
      - name: webdir
        hostPath:
          path: /root/htdocs/
