---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-deploy
  labels:
    app: nginx-test-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test-pod
  template:
    metadata:
      labels:
        app: nginx-test-pod
    spec: 
      nodeSelector:
        app: dns
      containers:
      - name: nginx-test-container
        image: nginx:1.15
        ports:
        - containerPort: 80
        volumeMounts:
        - name: timefile
          mountPath: /etc/localtime
        - name: webdir
          mountPath: /usr/share/nginx/html

      volumes:
      - name: timefile
        hostPath:
          path: /etc/localtime
      - name: webdir
        hostPath:
          path: /root/htdocs/
