---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-deploy
  labels:
    app: nginx-test-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-test-pod
  template:
    metadata:
      labels:
        app: nginx-test-pod
    spec: 
      containers:
      - name: nginx-test-container
        image: nginx:1.17
        ports:
        - containerPort: 80
        volumeMounts:
        - name: timefile
          mountPath: /etc/localtime
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi

      volumes:
      - name: timefile
        hostPath:
          path: /etc/localtime
