apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql

    spec:
      nodeSelector:
        server: mysql
      containers:
        - name: mysql
          image: mysql:5.7
          env:
          - name: LANG
            value: en_US.UTF-8
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
          volumeMounts:
          - name: mysql-conf-d
            mountPath: /etc/mysql/conf.d
          - name: mysql-mysql-conf-d
            mountPath: /etc/mysql/mysql.conf.d
          - name: datadir
            mountPath: /var/lib/mysql
          - name: timefile
            mountPath: /etc/localtime
            readOnly: true
      volumes:
      - name: mysql-conf-d
        configMap:
          name: mysql-conf-d
      - name: mysql-mysql-conf-d     
        configMap:
          name: mysql-mysql-conf-d
      - name: datadir
        persistentVolumeClaim:
          claimName: mysql-pvc1
      - name: timefile
        hostPath: 
          path: /etc/localtime
