---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    app: traefik
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      nodeSelector:
        app: traefik
      containers:
      - name: traefik-ingress-lb
        image: traefik:1.7
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: admin
          containerPort: 8080
          hostPort: 8080
        volumeMounts:
        - name: timefile
          mountPath: /etc/localtime
        #- name: traefik
        #  mountPath: /etc/traefik/
        args:
          - --api
          - --kubernetes
          - --logLevel=DEBUG


      volumes:
      - name: timefile
        hostPath:
          path: /etc/localtime
      - name : traefik
        configMap:
          name: traefik
        
