---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-ingress-controller
  namespace: default
  labels:
    app: traefik
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      nodeSelector:
        app: traefik
      containers:
      - name: traefik-ingress-lb
        image: traefik:2.0
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8080
          hostPort: 8080
        - name: mysql
          containerPort: 3306
          hostPort: 3306
        volumeMounts:
        - mountPath: /etc/localtime
          name: timefile
        - mountPath: /config
          name: config
        args:
        - --configfile=/config/traefik.toml
        #- --providers.kubernetesingress=true
        #- --providers.kubernetesingress.endpoint=https://10.254.0.1:443
        #- --api.insecure=true
        #- --log=true
        #- --log.level=INFO
        #- --providers.kubernetesingress.ingressclass=traefik-test

      volumes:
      - name: timefile
        hostPath:
          path: /etc/localtime
      - name: config
        configMap:
          name: traefik-conf
