---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gearmand
  labels:
    app: gearmand
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gearmand
  template:
    metadata:
      labels:
        app: gearmand
    spec:
      containers:
      - name: gearmand
        image: xg.cc/gearmand:1.1
        imagePullPolicy: IfNotPresent
        args:
        - run
        ports:
        - containerPort: 4730
        volumeMounts:
        - name: timefile
          mountPath: /etc/localtime
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi

      volumes:
      - name: timefile
        hostPath:
          path: /etc/localtime

