apiVersion: v1
kind: Pod
metadata:
  name: gearmand
spec:
  nodeName: test101
  containers:
  - name: gearmand
    image: xg.cc/gearmand:1.1
    imagePullPolicy: IfNotPresent
    command: ["gearmand","--round-robin", "-t", "2","-j","0","-w", "0","--verbose=DEBUG", "--log-file=/dev/stdout"]
    ports:
    - containerPort: 4730

