apiVersion: v1
kind: Pod
metadata:
  name: gearmand
spec:
  nodeName: test101
  containers:
  - name: gearmand
    image: artefactual/gearmand:1.1.18-alpine
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 4730

